using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Imani.Solutions.Core.API.Util;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace steeltoe.data.showcase.src.Migrations
{
    public class SampleContextSchemaMigration
    {
        private const string schemaName = "Sample";

        const string  MIGRATION_SQL = $@"
        CREATE SCHEMA IF NOT EXISTS {schemaName};

        CREATE TABLE IF NOT EXISTS {schemaName}.__EFMigrationsHistory (
        MigrationId character varying(150) NOT NULL,
        ProductVersion character varying(32) NOT NULL,
        CONSTRAINT PK___EFMigrationsHistory PRIMARY KEY (MigrationId)
        );

        START TRANSACTION;

        CREATE TABLE IF NOT EXISTS {schemaName}.TestData (
            Id integer GENERATED BY DEFAULT AS IDENTITY,
            Data text NULL,
            CONSTRAINT data_id PRIMARY KEY (Id)
        );

        INSERT INTO {schemaName}.__EFMigrationsHistory (MigrationId, ProductVersion)
        VALUES ('20230909025305_InitialCreate', '7.0.10') 
        ON conflict (MigrationId) DO NOTHING;

        COMMIT;";

        internal void Migrate(DatabaseFacade database)
        {
            
             database.ExecuteSqlRaw(MIGRATION_SQL);
        }
    }
}